from main import redis, Product
import time

key = "order_completed"
group = "inventory-group"

try:
    redis.xgroup_create(key, group)
except:
    print("Error: this product already exists")

while True:
    try: 
        res = redis.xreadgroup(group, key, {key: ">"}, None) # {key: ">"} = lisen all the events
        
        if res != []:
            for result in res:
                obj = result[1][0][1]
                # If the product don't exists calls the refund order
                try:
                    product = Product.get(obj["product_id"])
                    print(f"Not modified product: {product}")
                    product.quantity = product.quantity - int(obj["quantity"])
                    product.save()
                except:
                    redis.xadd("refund_order", obj, "*") # Autogenerated ID (*)

                print(f"Modified product: {product}")
        print (f"result: {res}")
    except Exception as e:
        print(f"Error: {str(e)}")
    time.sleep(2)
